ProjectName:
  -pytest自动化测试框架

Env: 云业务测试环境
# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
TesterName: 朱宏玉

# 域名1
host: https://aecloud-test.glodon.com
# 域名2，支持多个域名配置
app_host: https://www.baidu.com


# 报告通知类型：0: 不发送通知 1：钉钉 2：企业微信通知 3、邮箱通知 4、飞书通知
NotificationType: 3

# 收集失败的用例开关，整理成excel报告的形式，自动发送，目前只支持返送企业微信通知
excel_report: False

# 注意点：
# 之前为了小伙伴们拉下代码执行的时候不受影响，企业微信、钉钉、邮箱的通知配置的都是我的
# 我发现很多拉代码的小伙伴这里配置都没改，所有的通知都发到我这里来了哦~~麻烦看到这里的小伙伴自己改一下相关配置

# 钉钉相关配置
DingTalk:
  webhook:
  secret:

# 数据库相关配置
MySqlDB:
  # 数据库开关
  switch: False
  host:
  user: dev
  password:
  db:

# 镜像源
mirror_source: http://mirrors.aliyun.com/pypi/simple/

# 企业通知的相关配置
WeChat:
  webhook:

email:
  send_user: zhuhongyu.2009@163.com
  email_host: smtp.163.com
  stamp_key: VIOILTUYHXAQFOEK
  # 收件人
  send_list: zhuhongyu.2009@163.com

# 飞书通知
FeiShuTalk:
  webhook:

# 实时更新用例内容，False时，已生成的代码不会在做变更
# 设置为True的时候，修改yaml文件的用例，代码中的内容会实时更新
real_time_update_test_cases: False

